title: Give Me a Break
#description: 30 min. to 1 hour dog-walking services, including some play and basic training to help tire out your dog when you need it most.
#show_downloads: false
theme: jekyll-theme-minima
